json.id product.id
json.name product.name
json.price product.price
json.description product.description
json.discounted product.is_discounted?
json.tax product.tax
json.total product.total
json.supplier_id product.supplier_id
json.supplier_info product.supplier
json.image_urls product.image
json.current_user current_user.id